unit CustomerU;

interface

uses MVCFramework.Serializer.Commons, MVCFramework.ActiveRecord,
  MVCFramework.Nullables;

type
  TEntityBase = class abstract(TMVCActiveRecord)
  protected
    [MVCTableField('id', [foPrimaryKey, foAutoGenerated])]
    fID: Integer;
  public
    property ID: Integer read fID write fID;
  end;

  [MVCNameCase(ncLowerCase)]
  [MVCTable('customers')]
  TCustomer = class(TEntityBase)
  private
    [MVCTableField('code')]
    fCode: string;
    [MVCTableField('city')]
    fCity: string;
    [MVCTableField('company')]
    fCompanyName: string;
  public
    property Code: string read fCode write fCode;
    property City: string read fCity write fCity;
    property CompanyName: string read fCompanyName write fCompanyName;
  end;


implementation


end.

